workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Give permission to gradlew
        script: |
          cd android
          chmod +x gradlew
      - name: Clean project
        script: |
          cd android
          ./gradlew clean
      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
