workflows:
  build_kotlin_apk:
    name: Build Kotlin Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        ANDROID_SDK_ROOT: /Users/builder/programs/android-sdk-macosx
      java: 17
      kotlin: 1.9.24

    scripts:
      - name: Prepare Gradle Wrapper
        script: chmod +x ./gradlew

      - name: Create local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Install Android SDK
        script: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-10406996_latest.zip
          unzip sdk-tools.zip -d latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Release APK
        script: ./gradlew :app:assembleRelease --stacktrace --info

    artifacts:
      - app/build/outputs/apk/release/app-release.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
