workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Give permission to gradlew
        script: |
          cd $CM_BUILD_DIR
          chmod +x ./gradlew
      - name: Clean project
        script: |
          cd $CM_BUILD_DIR
          ./gradlew :app:clean
      - name: Build Release APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew :app:assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
