workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Set up Gradle permissions
        script: |
          chmod +x ./gradlew
      - name: Build Release APK
        script: |
          ./gradlew :app:assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
