workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        ANDROID_SDK_ROOT: /Users/builder/programs/android-sdk-macosx
    scripts:
      - name: Permissions
        script: chmod +x ./gradlew
      - name: Setup Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" || true
      - name: Build Release APK
        script: |
          ./gradlew :app:assembleRelease --stacktrace --info
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
