workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Set permissions
        script: chmod +x ./gradlew
      - name: Install Android SDK 34
        script: |
          yes | sdkmanager "platforms;android-34"
      - name: Build Release APK
        script: |
          ./gradlew :app:assembleRelease --stacktrace --info
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
